### ISSUE TITLE
Finalize on data source

### ISSUE THREAD

**Issue by dshgna** [AndroidJamSriLanka/Rsvp_Mobile#1]
This is a very practical idea with great applicability. 

The only issue I have here is: how will you get the data? Is their an easy way to retrieve the data from the learning management system? Check if it is possible and revise as necessary.

**Comment by manee92** [comment]
Thanks Dulshani!!
I thought to change my app idea to RSVP_Mobile, an app to rsvp.lk , event management website.
They will provide APIs
